# Generated by Django 5.1 on 2024-09-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="descripcion",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="evento",
            name="ubicacion",
            field=models.TextField(default=""),
        ),
    ]
